sudo: required

services:
  - docker

language: generic

before_install:
  - travis_retry docker pull talex5/tla

script:
  - make
  - mkdir pdfs
  - cp *.pdf pdfs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  local-dir: pdfs

notifications:
  email: false
